@echo off
color A
title                                                                   Your Matrix 1.1
echo.
echo     Enter your text.
echo.
set input=
set /p input=
set /a ega=%input%
echo.
cls
:sas
echo %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input% %random% %input%
goto sas